# https://hub.docker.com/_/redis
FROM redis:8.8-m03
# COPY ./redis/redis.conf /usr/local/etc/redis/redis.conf
# COPY ./redis.conf /usr/local/etc/redis/redis.conf
# COPY redis.conf /usr/local/etc/redis/redis.conf
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
